# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the entire application directory to the container
COPY . /app

# Install the dependencies specified in the pyproject.toml
RUN pip install .

# Expose the port that the MCP server listens on
EXPOSE 8000

# Command to run the application
CMD ["python", "-m", "time_server"]
